/**
 * Project #2 (https://projecteuler.net/problem=2)
 * # Even Fibonacci numbers
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

 const problem = {
  title: "Even Fibonacci numbers",
  url: "https://projecteuler.net/problem=2",
  arguments: [
    {name: 'num', type: 'number', default: 1000}
  ],
  solution: <T>(num: T) => {
    if (typeof num === 'number') {
      const fib = [0, 1];
      let sum = 0;

      for (let i = 2; i < Infinity; i++) {
        const newFib = fib[i-2] + fib[i-1]
        if (newFib > num) {
          break;
        }
        fib.push(newFib);
        if (newFib % 2 === 0) {
          sum = sum + newFib;
        }
      }

      console.log(sum)
    }
  }
}

export default problem